version: 2

models:
  - name: stg_treks
    columns:
      - name: trek_id
        quote: true
        tests:
          - not_null
          - unique

  - name: stg_weather
    columns:
      - name: trek_id
        quote: true
        tests:
          - not_null

  - name: int_trek_weather
    columns:
      - name: trek_id
        quote: true
        tests:
          - not_null

  - name: trek_analytics
    columns:
      - name: trek_id
        quote: true
        tests:
          - not_null