-- 1. Check integration
DESC INTEGRATION TREK_S3_INTEGRATION;

-- 2. Trek stage
CREATE OR REPLACE STAGE TREK_ANALYTICS.TREK_GOLD_STAGE
URL = 's3://ayush-uttarakhand-trek-intelligence/gold/treks/'
STORAGE_INTEGRATION = TREK_S3_INTEGRATION
FILE_FORMAT = (TYPE = PARQUET);

LIST @TREK_ANALYTICS.TREK_GOLD_STAGE;

-- 3. Parquet format
CREATE OR REPLACE FILE FORMAT TREK_ANALYTICS.TREK_PARQUET_FORMAT
TYPE = PARQUET;

-- 4. Check schema
SELECT *
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@TREK_ANALYTICS.TREK_GOLD_STAGE',
        FILE_FORMAT => 'TREK_ANALYTICS.TREK_PARQUET_FORMAT'
    )
);

-- 5. Create trek table
CREATE OR REPLACE TABLE TREK_ANALYTICS.TREKS_GOLD
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    WITHIN GROUP (ORDER BY ORDER_ID)
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@TREK_ANALYTICS.TREK_GOLD_STAGE',
            FILE_FORMAT => 'TREK_ANALYTICS.TREK_PARQUET_FORMAT'
        )
    )
);

-- 6. Load treks
COPY INTO TREK_ANALYTICS.TREKS_GOLD
FROM @TREK_ANALYTICS.TREK_GOLD_STAGE
FILE_FORMAT = (TYPE = PARQUET)
PATTERN = '.*part-.*\.parquet'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

-- 7. Trek count
SELECT COUNT(*) AS total_rows,
       COUNT(DISTINCT "trek_id") AS unique_treks
FROM TREK_ANALYTICS.TREKS_GOLD;

-- 8. Remove null IDs
DELETE FROM TREK_ANALYTICS.TREKS_GOLD
WHERE "trek_id" IS NULL;

-- 9. Verify treks
SELECT COUNT(*) AS total_rows,
       COUNT(DISTINCT "trek_id") AS unique_treks
FROM TREK_ANALYTICS.TREKS_GOLD;

SELECT *
FROM TREK_ANALYTICS.TREKS_GOLD
ORDER BY "trek_id"
LIMIT 10;


-- 10. Weather stage
CREATE OR REPLACE STAGE TREK_ANALYTICS.WEATHER_GOLD_STAGE
URL = 's3://ayush-uttarakhand-trek-intelligence/gold/weather/'
STORAGE_INTEGRATION = TREK_S3_INTEGRATION
FILE_FORMAT = (TYPE = PARQUET);

LIST @TREK_ANALYTICS.WEATHER_GOLD_STAGE;

-- 11. Weather format
CREATE OR REPLACE FILE FORMAT TREK_ANALYTICS.PARQUET_FORMAT
TYPE = PARQUET;

-- 12. Check weather schema
SELECT *
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@TREK_ANALYTICS.WEATHER_GOLD_STAGE',
        FILE_FORMAT => 'TREK_ANALYTICS.PARQUET_FORMAT'
    )
);

-- 13. Create weather table
CREATE OR REPLACE TABLE TREK_ANALYTICS.WEATHER_GOLD
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    WITHIN GROUP (ORDER BY ORDER_ID)
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@TREK_ANALYTICS.WEATHER_GOLD_STAGE',
            FILE_FORMAT => 'TREK_ANALYTICS.PARQUET_FORMAT'
        )
    )
);

-- 14. Load weather
COPY INTO TREK_ANALYTICS.WEATHER_GOLD
FROM @TREK_ANALYTICS.WEATHER_GOLD_STAGE
FILES = (
    'part-00000-a132f0da-478a-4b01-b984-b6463f947c72-c000.snappy.parquet'
)
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

-- 15. Weather count
SELECT COUNT(*) AS total_weather_rows
FROM TREK_ANALYTICS.WEATHER_GOLD;

-- 16. Weather preview
SELECT *
FROM TREK_ANALYTICS.WEATHER_GOLD
LIMIT 10;